#hello

events {}

http {
    server {
        listen 80;

        location /api1 {
            proxy_pass http://api1:5001;
	    rewrite ^/api1(/.*)$ $1 break;
        }

        location /api2 {
            proxy_pass http://api2:5002;
        }
    }
}

